### ISSUE TITLE
problema appelli prenotati

### ISSUE THREAD

**Issue by CDeRita** [myunimol/webapp#11]
## ![schermata da 2015-01-24 11 14 53](https://cloud.githubusercontent.com/assets/10024395/5887035/19e69218-a3bc-11e4-8567-d2f8a971e9d4.png)

![schermata da 2015-01-24 11 22 42](https://cloud.githubusercontent.com/assets/10024395/5887036/1d11b666-a3bc-11e4-8dca-e846eaf1c8a4.png)

![schermata da 2015-01-24 11 23 12](https://cloud.githubusercontent.com/assets/10024395/5887037/24114404-a3bc-11e4-8443-9648d1851cf2.png)

**Comment by GiusWhite** [comment]
E qual'è il problema?

**Comment by CDeRita** [comment]
È descritto nella issue "Failure News - Appelli "

---- Giuseppe Bianco ha scritto ----

E qual'è il problema?

---

**Comment by GiusWhite** [comment]
Ho controllato la risposta della chiamata POST a GetEnrolledExamsServlet, e non ritorna alcun risultato.
Così sono andato a lanciare direttamente la servlet da WebServices, ed il risultato è stato un "HTTP Status 500 - String index out of range: -1"

![screenshot 2015-01-25 02 48 22](https://cloud.githubusercontent.com/assets/10000453/5889863/440e7520-a43d-11e4-94b3-5c185d40709f.png)

**Comment by mattmezza** [comment]
Il problema è relativo ai web services quindi lo riporto lì e chiudo la issue.
