### ISSUE TITLE
Mostrare spinner di caricamento fino al polymer-ready

### ISSUE THREAD

**Issue by mattmezza** [myunimol/webapp#12]
Stavo pensando che sarebbe opportuno mostrare uno spinner, una barra o anche una immagine (pure gif animata) prima che polymer diventi ready. Insomma fare in modo tale che questo 
![ios simulator screen shot jan 26 2015 2 47 57 pm](https://cloud.githubusercontent.com/assets/1915989/5900525/606f6520-a56a-11e4-86ea-4ca3b8be4986.png)
non accada più...

Si potrebbe racchiudere tutto il contenuto del `body` in un `div` con `display: none;` e inserire (accanto a questo `div`) un `div` contenente il messaggio di caricamento in corso. Poi nel `polymer-ready` effettuare lo switch di visibilità dei `div` una volta che _Polymer_ ha finito correttamente il caricamento.

Dovrebbe funzionare facendo così anche se non ho avuto modo di provare.

**Comment by CDeRita** [comment]
Mi sembra un ottima idea, effettivamente    è abbastanza brutto vedere quella cosa all'inizio...

---- Matteo Merola ha scritto ----

Stavo pensando che sarebbe opportuno mostrare uno spinner, una barra o anche una immagine (pure gif animata) prima che polymer diventi ready. Insomma fare in modo tale che questo
![ios simulator screen shot jan 26 2015 2 47 57 pm](https://cloud.githubusercontent.com/assets/1915989/5900525/606f6520-a56a-11e4-86ea-4ca3b8be4986.png)
non accada più...

Si potrebbe racchiudere tutto il contenuto del `body` in un `div` con `display: none;` e inserire (accanto a questo `div`) un `div` contenente il messaggio di caricamento in corso. Poi nel `polymer-ready` effettuare lo switch di visibilità dei `div` una volta che _Polymer_ ha finito correttamente il caricamento.

Dovrebbe funzionare facendo così anche se non ho avuto modo di provare.

---

Reply to this email directly or view it on GitHub:
https://github.com/giograno/myUnimol_webApp/issues/12

**Comment by mattmezza** [comment]
Grazie @GiusWhite questa issue si può chiudere!
