### ISSUE TITLE
Beta testing reporting system

### ISSUE THREAD

**Issue by mattmezza** [myunimol/webapp#14]
Ci servirebbe un sistema per tracciare bug, malfunzionamenti e opinioni degli utenti da integrare nella webapp. Tale sistema dovrebbe tracciare: 
- lo username dell'utente (per poterlo contattare via email);
- il browser che utilizza l'utente (nome e versione);
- nome e versione del SO;
- data e ora della segnalazione.

Procederemo con la prototipazione della UI relativa al sottosistema da realizzare al fine di far venire a galla eventuali informazioni necessarie e problematiche varie.
Dopodiché discuteremo sulle scelte tecniche per la realizzazione.

Intanto creiamo una discussione costruttiva sull'argomento :+1:

**Comment by intersimone999** [comment]
Secondo me possiamo aggiungere semplicemente una voce nel menu per il momento, in modo da non complicare troppo le cose.
Comunque penso che ci sia qualche libreria che permetta di gestire almeno l'UI in maniera automatica, faccio qualche ricerca!

**Comment by GiusWhite** [comment]
Una via di mezzo potrebbe essere una soluzione.
Ovvero una voce nel menu che porta ad una pagina con un semplice form.
Questo form prende in automatico l'user, permette di scegliere il dispositivo, il sistema operativo, il browser, l'eventuale pagina su cui si vuole effettuare la segnalazione ed un textfield per la descrizione.

**Comment by intersimone999** [comment]
Le informazioni su dispositivo, sistema operativo e browser potrebbero essere prese in automatico (user-agent di http). In definitiva potrebbero esserci questi campi:
- indirizzo email (il nome utente potrebbe non bastare)
- commento
- pagina di riferimento (come base possiamo usare il referrer http, ma con la possibilità di modificarlo)
- eventualmente un campo "tipologia" (in cui si può scegliere tra "bug", "consiglio" etc)

Manca qualcosa?

**Comment by mattmezza** [comment]
Dobbiamo cercare di far immettere agli utenti quante meno informazioni possibili altrimenti non manderanno mai nessuna segnalazione.
Quindi sono a favore della compilazione automatica e trasparente dei dettagli tecnici (versioni browser, SO, etc) e a favore della precompilazione della pagina target tramite il http-referrer.
Il nome utente è lo stesso delle email istituzionali @studenti.unimol.it quindi dovrebbe bastare. Meglio non chiedere troppo agli utenti altrimenti non lo compilano.
Dobbiamo ragionare sulle categorie e su un eventuale modo di riproduzione del bug, altrimenti tutto diventa inutile.
Non è solo un sistema per la validazione del workflow e della UI ma è anche un sistema per la scoperta di bug (che ci sono e molti sono nei webservices e nel parsing di esse3). Se non riusciamo a riprodurre la failure diventa difficile eliminare i difetti. :+1:

**Comment by mattmezza** [comment]
Ho iniziato a lavorare a una prima versione del sistema di reporting di bug. Si trova nella branch bugSystem, dateci un'occhiata.

**Comment by intersimone999** [comment]
Forse sarebbe meglio togliere un po' di cose (es la faccina), ma per quanto riguarda i contenuti e lo stile in genere e i campi da compilare penso che vada bene :+1:

**Comment by mattmezza** [comment]
Mi chiedevo, in fase di sottomissione, si manda una mail del bug report o si inserisce la segnalazione in un dbms (mysql o mongodb)?

**Comment by GiusWhite** [comment]
Secondo me la soluzione migliore sarebbe salvarla in un dbms, ed avere un eventuale "pannello di controllo" per poter consultare le varie segnalazioni.
Con le mail è sicuramente più semplice, ma sarebbe più difficile gestirle.

**Comment by mattmezza** [comment]
ho continuato il lavoro, nello specifico ho aggiunto:
- modulo web per segnalazione problemi;
- modulo web per segnalazione suggerimenti;
- storage persistente tramite mongodb di problemi e suggerimenti.

_Ho aggiunto la libreria per i Driver di mongodb_ ma ovviamente questa deve essere aggiunta manualmente tramite IDE nel build path di Java.

Mancano:
- nome e versione browser;
- nome e versione SO;
- data e ora segnalazione;
- **revisione** (non so se sono stato esaustivo o appropriato);
- **testing**.

Quando riuscite a dare una occhiata fatemi sapere che ne pensate.

**Comment by mattmezza** [comment]
sufficiente, chiudo
