### ISSUE TITLE
Posizione variabile dello spinner Polymer

### ISSUE THREAD

**Issue by intersimone999** [myunimol/webapp#15]
Lo spinner Polymer viene mostrato al centro del div a cui fa riferimento, per questo la sua posizione è variabile, e a volte è più sopra, altre addirittura non si vede affatto, perché il centro è troppo in basso, fuori dai bordi dello schermo (in "Rubrica", ad esempio).
Bisognerebbe trovare un modo per mostrarlo sempre al centro correttamente.

**Comment by mattmezza** [comment]
Per spinner ti riferisci allo spinner che viene mostrato attraverso la funzione `freeze(...)` che serve a mostrare il caricamento della chiamata ajax?

**Comment by intersimone999** [comment]
Sì esatto, quello spinner. Può creare confusione il fatto di non vedere nulla in alcune occasioni.
