### ISSUE TITLE
Uniformare stile grafico delle pagine

### ISSUE THREAD

**Issue by GiusWhite** [myunimol/webapp#16]
Credo che uniformare lo stile delle pagine a quello della home (sfondo grigio, contenuto del rettangolo bianco) renda tutto più elegante.
Voi cosa ne dite?

**Comment by CDeRita** [comment]
Si anche secondo me sarebbe meglio.

---- Giuseppe Bianco ha scritto ----

**Comment by mattmezza** [comment]
Senza dubbio! Lo stile della Home sarebbe perfetto secondo me! Ci servirebbe qualcuno che creasse qualcosa di unico, uno style.css integrato e utilizzabile da tutte le pagine, **qualcuno riesce a darci una occhiata**?

**Comment by GiusWhite** [comment]
Ci penso io :v:

**Comment by mattmezza** [comment]
Ottimo, grande @GiusWhite! :+1: 
Appena hai risultati notificalo così cerchiamo di essere quanto più reattivi possibile (anche se questo periodo non è dei migliori in quanto a tempo disponibile)
