### ISSUE TITLE
Login Servlet Error

### ISSUE THREAD

**Issue by GiusWhite** [myunimol/webapp#18]
Il login non funziona.
Provando ad effettuare il login (branch develop) è impossibile effettuare l'accesso con "pippo".

Al momento della chiamata ajax la LoginServlet restituisce un Error 500: Json Exception

![screenshot 2015-02-10 09 31 56](https://cloud.githubusercontent.com/assets/10000453/6123905/6834771a-b108-11e4-9c73-be9f2534f569.png)

**Comment by mattmezza** [comment]
È ancora presente questo bug?

**Comment by mattmezza** [comment]
scusa, duplicato di #19 quindi chiudo.
