### ISSUE TITLE
Login Servlet Error

### ISSUE THREAD

**Issue by GiusWhite** [myunimol/webapp#19]
È impossibile effettuare il login (branch develop) con le credenziali "pippo".

Al momento della chiamata la LoginServlet restituisce un Error 500: Json Exception

![screenshot 2015-02-10 09 31 56](https://cloud.githubusercontent.com/assets/10000453/6123927/c2e8ed62-b108-11e4-8b55-4c23be4c19a1.png)

**Comment by intersimone999** [comment]
Se vuoi testare in locale, modifica il file di configurazione in MyUnimolWebApp, ovvero Web/META-INF/config.properties, e metti "betatest" a "false"

**Comment by mattmezza** [comment]
Quello che ha detto Simone ha risolto il problema? Se sì chiudiamo questa Issue :+1:

**Comment by GiusWhite** [comment]
Risolto.
È un problema di configurazione del file config.properties.
Chiunque abbia questo problema, controllasse il valore di "betatest" e "root".
