### ISSUE TITLE
Bug nella Login in versione mobile - Visualizzazione footer informtivo

### ISSUE THREAD

**Issue by VincenzoFerrigno** [myunimol/webapp#3]
Accedendo all'applicazione con lo smartphone, nella schermata di Login, non viene visualizzato il footer informativo.

Smartphone: Google LG Nexus 5
Sistema Operativo: Android Lollipop 5.0.1
Browser: Google Chrome

Screenshot del bug:
![screenshot1](https://cloud.githubusercontent.com/assets/10632207/5837717/c18f3fe8-a181-11e4-9108-147d3deaf171.png)

**Comment by mattmezza** [comment]
In questo caso... 

> "Non è un bug ma è una feature..." (Cit.) 

poiché il footer viene settato a `display: none;` per questioni di spazio.

Si potrebbe lavorare a una versione che mostri il footer più in basso rispettando le proporzioni per evitare malfunzionamenti con gli schermi più piccoli.

Qualcuno può produrre una versione della pagina di Login in questo senso?

**Comment by mattmezza** [comment]
in questo file [https://github.com/giograno/myUnimol_webApp/blob/master/web/Login.jsp](https://github.com/giograno/myUnimol_webApp/blob/master/web/Login.jsp) nelle righe dopo la 188esima ci sono i controlli (di cui parlo nel commento precedente) sulla grandezza della finestra per nascondere elementi che potrebbero inficiare la visualizzazione per schermi piccoli.

**Comment by GiusWhite** [comment]
Posso occuparmene io
Il 21/gen/2015 15:34 "Matteo Merola" notifications@github.com ha scritto:

**Comment by mattmezza** [comment]
Bene! Sai fare una pull request su GitHub?

Ti elenco i passi che devi eseguire:
- dalla [pagina principale](https://github.com/giograno/myUnimol_webApp) clicca sul tasto Fork in alto a destra – si creerà una copia della repository di tua proprietà;
- scarica la repository di tua proprietà in locale;
- fai i cambiamenti che vuoi (solo quelli necessari alla risoluzione di questa issue);
- quando sei soddisfatto fai `commit` dei cambiamenti e sincronizza le repository (tutto con l'applicazione di Github);
- sempre da GitHub fai una Pull Request;
- se arrivi a questo punto diventerai contributor sulla repository ufficiale!

###### se non riesci a fare una pull request modifica quanti meno file puoi e alla fine manda una mail a noi 4 manager per procedere all'integrazione.

Grazie per il supporto :+1:

**Comment by mattmezza** [comment]
@GiusWhite [qui](https://help.github.com/articles/using-pull-requests/) trovi una guida by GitHub su come contribuire in un progetto open source. 
[Qui](https://www.atlassian.com/git/tutorials/making-a-pull-request) trovi una guida sullo stesso argomento fatta da Atlassian.

Sono tutte e due in inglese. Spero ti possano essere d'aiuto.

**Comment by mattmezza** [comment]
Ho mergiato i cambiamenti di @GiusWhite proposti in #8 nella branch develop. Appena è stabile la mergio in master. Nel frattempo chiudo questa issue.
