### ISSUE TITLE
Failure News - Appelli

### ISSUE THREAD

**Issue by CDeRita** [myunimol/webapp#5]
Attualmente la sezione avvisi nelle news e la sezione prenotati in appelli sembrano non funzionare più.

![schermata da 2015-01-22 12 26 16](https://cloud.githubusercontent.com/assets/10024395/5854812/fe7b463a-a231-11e4-997a-c182618dced6.png)

![schermata da 2015-01-22 12 26 32](https://cloud.githubusercontent.com/assets/10024395/5854814/032afd60-a232-11e4-939c-8c43005c9830.png)

**Comment by mattmezza** [comment]
Il problema è che da http://dipbioter.unimol.it/blog/categorie/bacheca-informatica/ sono sparite le news! Di conseguenza MyUnimol non trova nessuna news. 

Alla webapp manca il controllo "se non ci sono news stampa messaggio «nessuna news trovata»". 

##### Qualcuno vuole occuparsi di questo?

Per quanto riguarda gli appelli prenotati, @CDeRita puoi caricare il codice html che esse3 restituisce quando visualizzi gli esami prenotati? Aiuterebbe a replicare il bug e a risolverlo. 

Magari fai una nuova issue visto che in questa sono in corso discussioni per due problemi riscontrati. Potresti creare una issue "problema appelli prenotati" in cui carichi la schermata di esse3 relativa agli esami prenotati e il codice html di tale schermata (puoi oscurare e modificare le parti riguardanti i tuoi dati sensibili). Inserisci anche una descrizione del problema e vediamo di capire dove si annida questo difetto.
