### ISSUE TITLE
Feature notifica capslock attivo su input password

### ISSUE THREAD

**Issue by CDeRita** [myunimol/webapp#6]
Credo non sia male aggiungere un qualcosa che notifichi se il capslock è attivo quando viene selezionato l'input password nella login.

**Comment by mattmezza** [comment]
Personalmente lo ritengo poco utile (non solo in questo caso ma in generale) per i seguenti motivi:
- uso da mobile:
  - quando si digita la password da mobile, ogni carattere viene prima mostrato in chiaro e poi oscurato dando così la possibilità di rendersi conto di che carattere si sta inserendo;
  - il posizionamento di una eventuale notifica sarebbe difficoltoso data la dimensione esigua dello schermo;
  - solitamente questa funzionalità è demandata al sistema operativo.
- uso da desktop:
  - solitamente le tastiere dispongono di un indicatore luminoso per il caps lock;
  - prima di inserire la password si deve inserire lo username, permettendo così all'utente di rendersi conto dell'abilitazione o meno del caps lock.

Si deve tener presente che la notifica di caps lock abilitato dovrebbe praticamente essere sempre visibile in quanto (almeno per le credenziali vecchie) le password sono tutte in maiuscolo.

###### Ad ogni modo, puoi presentare un prototipo grafico di come inseriresti la notifica di caps lock attivo? Aiuteresti la decisione sull'inserimento o meno di questa feature nelle prossime release.

**Comment by CDeRita** [comment]
Credo abbia ragione, forse alla fine non è molto utile...
