### ISSUE TITLE
Inserire avviso se non viene trovata nessuna news

### ISSUE THREAD

**Issue by mattmezza** [myunimol/webapp#7]
Nella sezione news bisogna implementare dei cambiamenti affinché, se dopo aver consumato la API per il recupero delle news si ottiene come risposta un array vuoto di news (ossia se non ci sono news) un messaggio venga stampato.

La tipologia di messaggio e le modalità con cui dovrebbe apparire dovrebbero essere in linea con il messaggio che appare quando nessun appello disponibile è stato trovato, oppure quando nessun contatto è stato trovato con la stringa ricercata.

L'implementazione di tale modifica risolverebbe il problema in #5 .

**Comment by GiusWhite** [comment]
Ci penso io

**Comment by mattmezza** [comment]
:+1: ottimo
